### ISSUE TITLE
frobby optional spkg doesn't build on a lot of machines

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#7436]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/7436">trac #7436</a>.

On many Linux boxes, building the frobby-0.7.6 spkg fails as follows:

```
gcc version 4.4.1 (Ubuntu 4.4.1-4ubuntu8) 
****************************************************
mkdir -p bin/release/ 
g++ -Wall -ansi -pedantic -Wextra -Wno-uninitialized -Wno-unused-parameter -Werror -isystem /tmp/wstein/farm/sage-4.2.1.alpha0/loc
al/include -O3 -c src/main.cpp -o bin/release/main.o
src/main.cpp: In function ‘int main(int, const char**)’:
src/main.cpp:30: error: ‘srand’ was not declared in this scope
make: *** [bin/release/main.o] Error 1
Error building Frobby.

real    0m2.271s
user    0m0.320s
sys     0m0.410s
sage: An error occurred while installing frobby-0.7.6
```

I ran the command "sage -i frobby-0.7.6" on the build farm and it fails on:
- debian32/64
- fedora32/64
- mandriva32/64
- opensuse32/64
- ubuntu32/64

It works on centos (=REDHAT).    It works on sage.math.   Basically it works with gcc <= 4.2 and fails with newer GCC's. 

Reported by: was

Component: optional packages

CC: 

Report Upstream: N/A

Authors: 

Dependencies: 

Work issues: 

Reviewers: Benjamin Jones

Merged in: 

Attachments: <ol></ol>
