### ISSUE TITLE
Sage 4.4.1: the symmetrica Sage library cython code doesn't build on OS X 10.4 PowerPC, Intel

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#8837]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/8837">trac #8837</a>.

```
gcc -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/malloc/ -I/home/wstein/screen/varro/sage-4.4.1.alpha3/local//include -I/home/wstein/screen/varro/sage-4.4.1.alpha3/local//include/csage -I/home/wstein/screen/varro/sage-4.4.1.alpha3/devel//sage/sage/ext -I/home/wstein/screen/varro/sage-4.4.1.alpha3/local/include/python2.6 -c sage/libs/symmetrica/symmetrica.c -o build/temp.macosx-10.4-ppc-2.6/sage/libs/symmetrica/symmetrica.o -w
gcc -L/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib -bundle -undefined dynamic_lookup build/temp.macosx-10.4-ppc-2.6/sage/libs/symmetrica/symmetrica.o -L/home/wstein/screen/varro/sage-4.4.1.alpha3/local//lib -lcsage -lsymmetrica -lstdc++ -lntl -o build/lib.macosx-10.4-ppc-2.6/sage/libs/symmetrica/symmetrica.so
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: multiple definitions of symbol _content
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libcsage.dylib(single module) definition of _content
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libsymmetrica.a(nu.o) definition of _content in section (__TEXT,__text)
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: multiple definitions of symbol _det
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libcsage.dylib(single module) definition of _det
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libsymmetrica.a(nu.o) definition of _det in section (__TEXT,__text)
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: multiple definitions of symbol _ggt
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libcsage.dylib(single module) definition of _ggt
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libsymmetrica.a(nu.o) definition of _ggt in section (__TEXT,__text)
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: multiple definitions of symbol _rank
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libcsage.dylib(single module) definition of _rank
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libsymmetrica.a(ma.o) definition of _rank in section (__TEXT,__text)
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: multiple definitions of symbol _jacobi
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libcsage.dylib(single module) definition of _jacobi
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libsymmetrica.a(nb.o) definition of _jacobi in section (__TEXT,__text)
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: multiple definitions of symbol _kronecker
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libcsage.dylib(single module) definition of _kronecker
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libsymmetrica.a(nb.o) definition of _kronecker in section (__TEXT,__text)
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: multiple definitions of symbol _print
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libcsage.dylib(single module) definition of _print
/home/wstein/screen/varro/sage-4.4.1.alpha3/local/lib/libsymmetrica.a(io.o) definition of _print in section (__TEXT,__text)
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
sage: There was an error installing modified sage library code.


real    12m5.293s
user    9m13.212s
sys     1m48.218s
make: *** [testlong] Error 1
varro:~/screen/varro wstein$ 
```

Reported by: was

Component: build

CC: 

Report Upstream: N/A

Authors: Georg S. Weber

Dependencies: 

Work issues: 

Reviewers: William Stein

Merged in: sage-4.4.1.final

Attachments: <ol></ol>
