### ISSUE TITLE
2.8.13: cddlib fails to build with gmp in /usr/local/ [OSX 10.4]

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#1252]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/1252">trac #1252</a>.

A remark: this ticket is now about cddlib miscompiling if there is a "rogue" gmp in /usr/local. The 10.5.1 issue is larger than gmp and now <a href="http://trac.sagemath.org/sage_trac/ticket/1253">trac #1253</a>.

Michael

Justin Walker reported:

```
I did a full build of 2.8.13 on two systems:

Mac OS X/10.4.11: Dual Quad-Core Xeon
Mac OS X/10.5.1:  Core Duo

Problems on both:
10.5.1: blow-up in Flint
   ld: duplicate symbol ___gmpz_abs in test-support.o and fmpz_poly-
test.o

10.4.11: blow-up in cddlib ("/usr/local" contamination)
   /usr/libexec/gcc/i686-apple-darwin8/4.0.1/ld: Undefined symbols:
   ___gmpq_init
   ...

FWIW, I used "-j6" on the 10.4 system and "-j2" on the 10.5 system.  
Rerunning the builds without the "j factor" gave me the (more or  
less) the same result on 10.4 and 10.5.

The full logs (of the "-j" builds) are in ~justin/logs on  
sage.math.washington.edu (tagged with 10.x).

Justin 
```

See http://groups.google.com/group/sage-devel/t/8e446357a1d15a8a

Cheers,

Michael

Reported by: mabshoff

Component: packages

CC: 

Report Upstream: 

Authors: ?

Dependencies: 

Work issues: 

Reviewers: 

Merged in: 

Attachments: <ol></ol>
