### ISSUE TITLE
get pynac to build with gcc-4.5.

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#8753]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/8753">trac #8753</a>.

Right now:

```
function.cpp:1886:29: warning: deprecated conversion from string constant to ‘char*’
function.cpp: In member function ‘GiNaC::ex GiNaC::function::power(const GiNaC::ex&) const’:
function.cpp:2186:15: error: expected type-specifier
function.cpp:2186:15: error: expected ‘)’
function.cpp:2187:72: error: conversion from ‘int*’ to ‘GiNaC::ex’ is ambiguous
ex.h:297:1: note: candidates are: GiNaC::ex::ex(long unsigned int) <near match>
ex.h:291:1: note:                 GiNaC::ex::ex(long int) <near match>
ex.h:285:1: note:                 GiNaC::ex::ex(unsigned int) <near match>
ex.h:273:1: note:                 GiNaC::ex::ex(int) <near match>
mv -f .deps/color.Tpo .deps/color.Plo


```

There is a new spkg posted on trac <a href="http://trac.sagemath.org/sage_trac/ticket/8644">trac #8644</a>, but it doesn't fix this.

Reported by: was

Component: build

CC: 

Report Upstream: N/A

Authors: William Stein

Dependencies: 

Work issues: 

Reviewers: Mike Hansen

Merged in: sage-4.4.1.alpha0

Attachments: <ol></ol>
