### ISSUE TITLE
graph_editor(p) should work for p a poset

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#8016]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/8016">trac #8016</a>.

Obviously `graph_editor(p)` doesn't work on its own, since `p` is not a graph. However, it should be possible to implement a few functions for `p` to make this work:

```
File "sage/graphs/graph_editor.py", line 111, in graph_editor
    if not isinstance(graph.get_pos(), dict):
AttributeError: 'FinitePoset' object has no attribute 'get_pos'
```

While wishing, it would also be nice if the graph editor could be adapted to remember vertex labels, at least in the case that the labels are strings.

Reported by: rlm

Component: combinatorics

CC: saliola,, rkirov,, mpatel

Report Upstream: N/A

Authors: 

Dependencies: 

Work issues: 

Reviewers: 

Merged in: 

Attachments: <ol></ol>
