### ISSUE TITLE
cremona-20071116.p0.spkg fails to build with gcc 4.2.x

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#1247]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/1247">trac #1247</a>.

 Andrzej Giniewicz reported:

```
 not counting plenty (281) warnings in file curvesort.cc (about
deprecated conversion from string constant to 'char*') I also get
WHOLE lot (about 8000) errors all in one nature:

../g0n/curvesort.cc:106: error: jump to case label
../g0n/curvesort.cc:105: error:   crosses initialization of 'int
<anonymous>[3]'

with different numbers only... problems starts from:

g++ -c -fPIC -g -O2 -DNEW_OP_ORDER -DUSE_PARI_FACTORING -I../include -
DNTL_ALL -I/opt/sage/local/include -I/opt/sage/local/include  tsat3.cc
-o tsat3_n.o
In file included from tsat3.cc:37:
../g0n/curvesort.cc ....... etc etc

I think there is no sense to attach such big report... I'm running
current Arch Linux, that is GCC 4.2.2, gLibc 2.7, kernel 2.6.23.8. Is
there some workaround? 
```

See http://groups.google.com/group/sage-support/t/c2140ece9608358e

Cheers,

Michael

Reported by: mabshoff

Component: packages

CC: 

Report Upstream: 

Authors: ?

Dependencies: 

Work issues: 

Reviewers: 

Merged in: 

Attachments: <ol></ol>
