### ISSUE TITLE
Singular fails to build on AIX 5.3

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#9993]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/9993">trac #9993</a>.

Singular is not building properly on the following hardware. If any Singular developer wants access to AIX to debug this, I can provide it. 

 == Hardware and software ==
- IBM [http://publib.boulder.ibm.com/infocenter/pseries/v5r3/index.jsp?topic=/com.ibm.pseries.doc/hardware_docs/rs6000_7025f50series.htm RS/6000 7025 F50]
- 4 x 332 MHz 32-bit PowerPC CPUs
- 3 GB RAM
- A fairly wide mixture of disks sizes (3 x 9 GB, 1 x 18 GB, 2 x 36 GB and 1 x 73 GB)
- DDS-4 tape drive 
- AIX 5.3 (A POSIX certified operating system)
- gcc 4.2.4 downloaded from [http://pware.hvcc.edu/ pware]
- sage-4.6.alpha1 (which has singular-3-1-1-4.p2)
  
  == The Problem ==
  As note, Singular fails to build. I see this _error_ a couple of times, but it does not abort the build. 

```
/opt/pware/lib/gcc/powerpc-ibm-aix5.3.0.0/4.2.4/../../../../include/c++/4.2.4/bits/ios_base.h:187: error: 'SEEK_CUR' was not declared in this scope
```

If eventually ends with:

```
polys-impl.h:177:1: warning: "pPolyAssumeReturn" redefined
polys-impl.h:176:1: warning: this is the location of the previous definition
make[4]: Target `install' not remade because of errors.
make[4]: Leaving directory `/home/users/drkirkby/sage-4.6.alpha1/spkg/build/singular-3-1-1-4.p2/src/kernel'
make[3]: *** [install] Error 1
make[3]: Leaving directory `/home/users/drkirkby/sage-4.6.alpha1/spkg/build/singular-3-1-1-4.p2/src'
make[2]: *** [/home/users/drkirkby/sage-4.6.alpha1/local/bin/Singular-3-1-1] Error 2
make[2]: Leaving directory `/home/users/drkirkby/sage-4.6.alpha1/spkg/build/singular-3-1-1-4.p2/src'
Unable to build Singular.

real    120m55.494s
user    164m57.036s
sys     2m3.365s
sage: An error occurred while installing singular-3-1-1-4.p2
```

Reported by: drkirkby

Component: AIX or HP-UX ports

CC: 

Report Upstream: N/A

Authors: 

Dependencies: 

Work issues: 

Reviewers: 

Merged in: 

Attachments: <ol></ol>
