### ISSUE TITLE
optional spkg nauty-24b7.p1  fails to build with sage-4.2.1 and ubuntu 9.10 (gcc-4.4.1)

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#7439]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/7439">trac #7439</a>.

With gcc version 4.4.1 (Ubuntu 4.4.1-4ubuntu8):

```
...
dreadnaut.c:983: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘unsigned int’
dreadnaut.c:985: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘unsigned int’
gcc -c -O4 -march=i686  gtools.c
In file included from gtools.c:6:
gtools.h:159: error: conflicting types for ‘getline’
/usr/include/stdio.h:651: note: previous declaration of ‘getline’ was here
gtools.c:375: error: conflicting types for ‘getline’
/usr/include/stdio.h:651: note: previous declaration of ‘getline’ was here
gtools.c: In function ‘gt_abort’:
gtools.c:1835: warning: format not a string literal and no format arguments
make: *** [gtools.o] Error 1
Copying nauty...
cp: cannot stat `addedgeg': No such file or directory
cp: cannot stat `amtog': No such file or directory
cp: cannot stat `biplabg': No such file or directory
cp: cannot stat `catg': No such file or directory
cp: cannot stat `complg': No such file or directory
cp: cannot stat `copyg': No such file or directory
cp: cannot stat `countg': No such file or directory
cp: cannot stat `deledgeg': No such file or directory
cp: cannot stat `directg': No such file or directory
cp: cannot stat `dretog': No such file or directory
cp: cannot stat `genbg': No such file or directory
cp: cannot stat `geng': No such file or directory
cp: cannot stat `genrang': No such file or directory
cp: cannot stat `labelg': No such file or directory
cp: cannot stat `listg': No such file or directory
cp: cannot stat `multig': No such file or directory
cp: cannot stat `newedgeg': No such file or directory
cp: cannot stat `NRswitchg': No such file or directory
cp: cannot stat `pickg': No such file or directory
cp: cannot stat `planarg': No such file or directory
cp: cannot stat `shortg': No such file or directory
cp: cannot stat `showg': No such file or directory

real    0m29.370s
user    0m10.093s
sys     0m18.105s
sage: An error occurred while installing nauty-24b7.p1
```

Reported by: was

Component: optional packages

CC: 

Report Upstream: Workaround found; Bug reported upstream.

Authors: Jason Grout

Dependencies: 

Work issues: 

Reviewers: Jason Grout, Paul Zimmermann

Merged in: 

Attachments: <ol></ol>
