### ISSUE TITLE
singular build error (sage 4.6.2)

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#10877]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/10877">trac #10877</a>.

Singular fails to build on Ubuntu 11.04 (Natty, 32-bit).
This is probably due to the changes in binutils for Natty/Wheezy (http://wiki.debian.org/ToolChain/DSOLinking)
which prevent the automatic resolution of symbols in indirect dependent shared libraries.

```
/usr/bin/ld: ../kernel/libkernel.a(mod_raw.o): undefined reference to symbol 'dlopen@@GLIBC_2.1'
/usr/bin/ld: note: 'dlopen@@GLIBC_2.1' is defined in DSO /usr/lib/gcc/i686-linux-gnu/4.5.2/../../../../lib/libdl.so so try adding it to the linker command line
/usr/lib/gcc/i686-linux-gnu/4.5.2/../../../../lib/libdl.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
```

Adding "-ldl" to LDFLAGS in spkg-install solves the problem.

Reported by: aapitzsch

Component: build

CC: 

Report Upstream: N/A

Authors: 

Dependencies: 

Work issues: 

Reviewers: 

Merged in: 

Attachments: <ol></ol>
