### ISSUE TITLE
optional package mpi4py-1.1.0.spkg does not build on sage-4.7.1.alpha1

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#11439]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/11439">trac #11439</a>.

The optional package mpi4py-1.1.0.spkg does not build on skynet/eno (x86_64-Linux-core2-fc) on sage-4.7.1.alpha1:

```
...
/usr/local/gcc-4.6.0/x86_64-Linux-core2-fc/bin/gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mariah/sage/sage-4.7.1.alpha1-x86_64-Linux-core2-fc/local/include/python2.6 -c src/MPI.c -o build/temp.linux-x86_64-2.6/src/MPI.o
In file included from src/MPI.c:3:0:
src/mpi4py.MPI.c:135:17: fatal error: mpi.h: No such file or directory
compilation terminated.
error: command '/usr/local/gcc-4.6.0/x86_64-Linux-core2-fc/bin/gcc' failed with exit status 1

real    0m0.392s
user    0m0.141s
sys     0m0.097s
sage: An error occurred while installing mpi4py-1.1.0
```

Reported by: mariah

Component: optional packages

CC: 

Report Upstream: N/A

Authors: 

Dependencies: 

Work issues: 

Reviewers: 

Merged in: 

Attachments: <ol></ol>
