### ISSUE TITLE
FLINT 1.0.6  fails to compile with gcc 4.3 prerelease [gmp.h releated]

### ISSUE THREAD

**Issue by sageb0t** [sageb0t/testsage#1415]
Imported from <a href="http://trac.sagemath.org/sage_trac/ticket/1415">trac #1415</a>.

I tried to compile Sage 2.9.alpha1 with:

```
gcc version 4.3.0 20071130 (experimental) [trunk revision 130545] (Debian 4.3-20071130-1) 
```

on my 64-bit x86 Linux Debian testing box, and compilation failed.

Here's the important chunk from the middle of the FLINT build log:

```
gcc -std=c99 -I/home/cwitty/gcc43-sage-2.9.alpha1/local/include/ -mtune=opteron -march=opteron -fPIC -funroll-loops  -O3 -c ZmodF_poly.c -o ZmodF_poly.o
gcc -std=c99 -I/home/cwitty/gcc43-sage-2.9.alpha1/local/include/ -mtune=opteron -march=opteron -fPIC -funroll-loops  -O3 -c long_extras.c -o long_extras.o
gcc -std=c99 -fPIC -shared -o libflint.so mpn_extras.o mpz_extras.o memory-manager.o ZmodF.o ZmodF_mul.o ZmodF_mul-tuning.o fmpz.o fmpz_poly.o mpz_poly-tuning.o mpz_poly.o ZmodF_poly.o long_extras.o -L/home/cwitty/gcc43-sage-2.9.alpha1/local/lib/  -lgmp -lpthread -lm
mpz_extras.o: In function `__gmpz_fits_uint_p':
mpz_extras.c:(.text+0x0): multiple definition of `__gmpz_fits_uint_p'
mpn_extras.o:mpn_extras.c:(.text+0x0): first defined here
mpz_extras.o: In function `__gmpz_fits_ulong_p':
mpz_extras.c:(.text+0x30): multiple definition of `__gmpz_fits_ulong_p'
mpn_extras.o:mpn_extras.c:(.text+0x30): first defined here
```

followed by many, many more "multiple definition" errors.

Presumably this is caused by the following (from the gcc 4.2 NEWS file):

```
- In the next release of GCC, 4.3, -std=c99 or -std=gnu99 will direct
  GCC to handle inline functions as specified in the C99 standard.  In
  preparation for this, GCC 4.2 will warn about any use of non-static
  inline functions in gnu99 or c99 mode.  This new warning may be
  disabled with the new gnu_inline function attribute or the new
  -fgnu89-inline command line option.  Also, GCC 4.2 and later will
  define one of the preprocessor macros __GNUC_GNU_INLINE__ or
  __GNUC_STDC_INLINE__ to indicate the semantics of inline functions
  in the current compilation.
```

Reported by: cwitty

Component: packages

CC: 

Report Upstream: 

Authors: ?

Dependencies: 

Work issues: 

Reviewers: 

Merged in: 

Attachments: <ol></ol>
